####################################################################
# github.com/jantman/workstation-bootstrap  -  User Configuration  #
#                                                                  #
# These variables must be updated for your specific configuration. #
####################################################################

# the username for your login user
username: jantman
# whether or not to purge all firewall rules at the global/firewall module level
firewall_purge: false
classes:
  - privatepuppet
remove_classes: []
